line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[format]
quote-style = "double"
indent-style = "space"